create table if not exists public.dashboard_versions (
  id uuid primary key default gen_random_uuid(),
  version_number bigint generated by default as identity unique,
  status text not null default 'draft' check (status in ('draft', 'published', 'archived')),
  source_file_name text not null,
  sheet_name text not null,
  record_count integer not null default 0,
  block_count integer not null default 0,
  total_amount_cents bigint not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users(id) on delete set null,
  published_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  published_at timestamptz
);

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;

create policy "Admins can read their own admin record"
  on public.admin_users
  for select
  to authenticated
  using (user_id = auth.uid());

create or replace function public.is_dashboard_admin()
returns boolean
language sql
stable
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_users
    where user_id = auth.uid()
  );
$$;

alter table public.financial_imports
  add column if not exists version_id uuid references public.dashboard_versions(id) on delete cascade;

alter table public.financial_records
  add column if not exists version_id uuid references public.dashboard_versions(id) on delete cascade;

create index if not exists dashboard_versions_status_idx on public.dashboard_versions(status);
create index if not exists dashboard_versions_created_at_idx on public.dashboard_versions(created_at desc);
create unique index if not exists dashboard_versions_single_published_idx
  on public.dashboard_versions((status))
  where status = 'published';

create index if not exists financial_imports_version_id_idx on public.financial_imports(version_id);
create index if not exists financial_records_version_id_idx on public.financial_records(version_id);
create index if not exists financial_records_version_group_idx on public.financial_records(version_id, group_key);
create index if not exists financial_records_version_group_department_idx
  on public.financial_records(version_id, group_key, department_key);

alter table public.dashboard_versions enable row level security;

drop policy if exists "Users can read their financial imports" on public.financial_imports;
drop policy if exists "Users can create their financial imports" on public.financial_imports;
drop policy if exists "Users can read their financial records" on public.financial_records;
drop policy if exists "Users can create their financial records" on public.financial_records;

create policy "Public can read published dashboard versions"
  on public.dashboard_versions
  for select
  to anon
  using (status = 'published');

create policy "Authenticated users can read dashboard versions"
  on public.dashboard_versions
  for select
  to authenticated
  using (public.is_dashboard_admin());

create policy "Authenticated users can create dashboard versions"
  on public.dashboard_versions
  for insert
  to authenticated
  with check (public.is_dashboard_admin() and created_by = auth.uid());

create policy "Authenticated users can update dashboard versions"
  on public.dashboard_versions
  for update
  to authenticated
  using (public.is_dashboard_admin())
  with check (public.is_dashboard_admin());

create policy "Admins can read financial imports"
  on public.financial_imports
  for select
  to authenticated
  using (public.is_dashboard_admin());

create policy "Admins can create financial imports"
  on public.financial_imports
  for insert
  to authenticated
  with check (public.is_dashboard_admin() and user_id = auth.uid());

create policy "Admins can read financial records"
  on public.financial_records
  for select
  to authenticated
  using (public.is_dashboard_admin());

create policy "Admins can create financial records"
  on public.financial_records
  for insert
  to authenticated
  with check (
    public.is_dashboard_admin()
    and exists (
      select 1
      from public.financial_imports fi
      where fi.id = financial_records.import_id
        and fi.user_id = auth.uid()
    )
  );

create policy "Public can read published financial records"
  on public.financial_records
  for select
  to anon
  using (
    exists (
      select 1
      from public.dashboard_versions dv
      where dv.id = financial_records.version_id
        and dv.status = 'published'
    )
  );

create policy "Public can read published financial imports"
  on public.financial_imports
  for select
  to anon
  using (
    exists (
      select 1
      from public.dashboard_versions dv
      where dv.id = financial_imports.version_id
        and dv.status = 'published'
    )
  );

create or replace function public.publish_dashboard_version(target_version_id uuid)
returns void
language plpgsql
set search_path = public
as $$
begin
  update public.dashboard_versions
  set status = 'archived'
  where status = 'published'
    and id <> target_version_id;

  update public.dashboard_versions
  set
    status = 'published',
    published_at = now(),
    published_by = auth.uid()
  where id = target_version_id;

  if not found then
    raise exception 'Dashboard version % was not found', target_version_id;
  end if;
end;
$$;

grant usage on schema public to anon, authenticated;
grant select on public.admin_users to authenticated;
grant select on public.dashboard_versions to anon, authenticated;
grant insert, update on public.dashboard_versions to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant select on public.financial_imports to anon, authenticated;
grant insert on public.financial_imports to authenticated;
grant select on public.financial_records to anon, authenticated;
grant insert on public.financial_records to authenticated;
grant execute on function public.is_dashboard_admin() to authenticated;
grant execute on function public.publish_dashboard_version(uuid) to authenticated;
