create table if not exists public.cash_flow_versions (
  id uuid primary key default gen_random_uuid(),
  version_number bigint generated by default as identity unique,
  status text not null default 'draft' check (status in ('draft', 'published', 'archived')),
  source_file_name text not null,
  month_label text not null,
  start_date date not null,
  end_date date not null,
  movement_count integer not null default 0,
  account_count integer not null default 0,
  initial_balance_cents bigint not null default 0,
  current_forecast_cents bigint not null default 0,
  dataset jsonb not null,
  metadata jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users(id) on delete set null,
  published_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  published_at timestamptz
);

create index if not exists cash_flow_versions_status_idx
  on public.cash_flow_versions(status);

create index if not exists cash_flow_versions_created_at_idx
  on public.cash_flow_versions(created_at desc);

create unique index if not exists cash_flow_versions_single_published_idx
  on public.cash_flow_versions((status))
  where status = 'published';

alter table public.cash_flow_versions enable row level security;

create policy "Public can read published cash flow versions"
  on public.cash_flow_versions
  for select
  to anon
  using (status = 'published');

create policy "Admins can read cash flow versions"
  on public.cash_flow_versions
  for select
  to authenticated
  using (public.is_dashboard_admin());

create policy "Admins can create cash flow versions"
  on public.cash_flow_versions
  for insert
  to authenticated
  with check (
    public.is_dashboard_admin()
    and created_by = auth.uid()
    and status = 'draft'
  );

create policy "Admins can update cash flow versions"
  on public.cash_flow_versions
  for update
  to authenticated
  using (public.is_dashboard_admin())
  with check (public.is_dashboard_admin());

create or replace function public.publish_cash_flow_version(target_version_id uuid)
returns void
language plpgsql
set search_path = public
as $$
begin
  if not public.is_dashboard_admin() then
    raise exception 'Only dashboard administrators can publish cash flow versions';
  end if;

  if not exists (
    select 1
    from public.cash_flow_versions
    where id = target_version_id
  ) then
    raise exception 'Cash flow version % was not found', target_version_id;
  end if;

  update public.cash_flow_versions
  set status = 'archived'
  where status = 'published'
    and id <> target_version_id;

  update public.cash_flow_versions
  set
    status = 'published',
    published_at = now(),
    published_by = auth.uid()
  where id = target_version_id;
end;
$$;

grant usage on schema public to anon, authenticated;
grant select on public.cash_flow_versions to anon, authenticated;
grant insert, update on public.cash_flow_versions to authenticated;
grant usage, select on sequence public.cash_flow_versions_version_number_seq to authenticated;
grant execute on function public.publish_cash_flow_version(uuid) to authenticated;
