create table if not exists public.cash_flow_reports (
  id uuid primary key default gen_random_uuid(),
  version_number bigint generated by default as identity unique,
  status text not null default 'draft' check (status in ('draft', 'published', 'archived')),
  source_file_name text not null,
  month_label text not null,
  start_date date not null,
  end_date date not null,
  movement_count integer not null default 0,
  daily_row_count integer not null default 0,
  anticipated_count integer not null default 0,
  variation_count integer not null default 0,
  initial_balance_cents bigint not null default 0,
  closing_balance_cents bigint not null default 0,
  dataset jsonb not null,
  metadata jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users(id) on delete set null,
  published_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  published_at timestamptz
);

create index if not exists cash_flow_reports_status_idx
  on public.cash_flow_reports(status);

create index if not exists cash_flow_reports_created_at_idx
  on public.cash_flow_reports(created_at desc);

create index if not exists cash_flow_reports_created_by_idx
  on public.cash_flow_reports(created_by);

create index if not exists cash_flow_reports_published_by_idx
  on public.cash_flow_reports(published_by);

create unique index if not exists cash_flow_reports_single_published_idx
  on public.cash_flow_reports((status))
  where status = 'published';

alter table public.cash_flow_reports enable row level security;

create policy "Public can read published cash flow reports"
  on public.cash_flow_reports
  for select
  to anon
  using (status = 'published');

create policy "Admins can read cash flow reports"
  on public.cash_flow_reports
  for select
  to authenticated
  using (public.is_dashboard_admin());

create policy "Admins can create cash flow reports"
  on public.cash_flow_reports
  for insert
  to authenticated
  with check (
    public.is_dashboard_admin()
    and created_by = (select auth.uid())
    and status = 'draft'
  );

create policy "Admins can update cash flow reports"
  on public.cash_flow_reports
  for update
  to authenticated
  using (public.is_dashboard_admin())
  with check (public.is_dashboard_admin());

create or replace function public.publish_cash_flow_report(target_version_id uuid)
returns void
language plpgsql
set search_path = public
as $$
begin
  if not public.is_dashboard_admin() then
    raise exception 'Only dashboard administrators can publish cash flow reports';
  end if;

  if not exists (
    select 1
    from public.cash_flow_reports
    where id = target_version_id
  ) then
    raise exception 'Cash flow report % was not found', target_version_id;
  end if;

  update public.cash_flow_reports
  set status = 'archived'
  where status = 'published'
    and id <> target_version_id;

  update public.cash_flow_reports
  set
    status = 'published',
    published_at = now(),
    published_by = (select auth.uid())
  where id = target_version_id;
end;
$$;

grant usage on schema public to anon, authenticated;
grant select on public.cash_flow_reports to anon, authenticated;
grant insert, update on public.cash_flow_reports to authenticated;
grant usage, select on sequence public.cash_flow_reports_version_number_seq to authenticated;
grant execute on function public.publish_cash_flow_report(uuid) to authenticated;
